### PR TITLE
Remove debug print.

### PR DESCRIPTION
**Pull request by cjwelborn**
This debug print shows on the client side. I was hoping it could be removed.

### CODE REVIEW

**Comment by calvinfroedge** [comment]
For sure = )  I'm actually doing a lot of refactoring now and will make sure I'm careful about that sort of thing.

**Comment by calvinfroedge** [comment]
@cjwelborn Checking the badge code on your website, I think this is what you want:

```
<github-badge user="cjwelborn" show_repos="true" show_languages="true" />
```

Sorry, I changed the API a bit to make it easier to maintain. Things are changing a lot right now but will be stabilizing soon, and there will be tests. Future releases will also be versioned. Thanks for bearing with me in the short term as I work through the chaos = )

**Comment by calvinfroedge** [comment]
@cjwelborn 

That code produces this:

cj

**Comment by cjwelborn** [comment]
I was wondering how to get that bigger look back. Thank you, I'll implement it as soon as I get off work.

**Comment by calvinfroedge** [comment]
Hey Chris,

I saw a few other issues associated with line-height on the contribution
graph being inherited, and the language / repos not being wide enough. That
should look good now = )

On Tue, Jun 9, 2015 at 12:37 PM, Christopher Welborn <
notifications@github.com> wrote:

> I was wondering how to get that bigger look back. Thank you, I'll
> implement it as soon as I get off work.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/deviant-io/github-user-badge/pull/1#issuecomment-110425713>
> .
>



-- 
Respectfully yours,
*Calvin Froedge*
Github <https://github.com/calvinfroedge> | LinkedIn
<http://www.linkedin.com/in/calvinfr>  |  (415) 494-9853

Recently released a Github Badge for displaying your project history
<http://bit.ly/1GoZFgi>... Would love feedback!

**Comment by cjwelborn** [comment]
It looks good. I can't see anything that I would change right now. I meant to say that the api changes don't bother me at all. My site is really just a place for me to experiment  with frontend/back end development, and host my little projects. I don't get a lot of traffic, or depend on it to make money, so if something is broken for a day or two it's not really a big deal (even if my OCD says otherwise). I appreciate you keeping me in the loop, and I will definitely recommend deviant.io over the others.

**Pull request merged**
